-- Supabase PostgreSQL Database Schema for Eventify Application
-- This script creates the database structure for the Eventify event management system
-- Compatible with Supabase PostgreSQL environment

-- Note: In Supabase, the database is already created. You can run this script in the Supabase SQL Editor.

-- Drop existing tables if they exist (for clean recreation)
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS venues CASCADE;

-- Create venues table with Supabase compatibility
CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name VARCHAR(255) NOT NULL,
    country VARCHAR(100),
    address VARCHAR(500),
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create events table with foreign key to venues and Supabase compatibility
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_title VARCHAR(255) NOT NULL,
    description TEXT,
    venue_id BIGINT NOT NULL,
    date VARCHAR(50), -- Consider changing to DATE type if specific date format is required
    event_hour TIME NOT NULL,
    price DECIMAL(10,2),
    hoster VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Foreign key constraint
    CONSTRAINT fk_venue 
        FOREIGN KEY(venue_id) 
        REFERENCES venues(id) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_events_venue_id ON events(venue_id);
CREATE INDEX idx_events_date ON events(date);
CREATE INDEX idx_events_title ON events(event_title);
CREATE INDEX idx_venues_name ON venues(venue_name);
CREATE INDEX idx_venues_city ON venues(city);

-- Create trigger function to automatically update updated_at timestamp (Supabase compatible)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_venues_updated_at 
    BEFORE UPDATE ON venues 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_events_updated_at 
    BEFORE UPDATE ON events 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS) for Supabase
ALTER TABLE venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Create RLS policies (adjust based on your authentication requirements)
-- Allow public read access to venues
CREATE POLICY "Venues are viewable by everyone." ON venues FOR SELECT USING (true);

-- Allow public read access to events
CREATE POLICY "Events are viewable by everyone." ON events FOR SELECT USING (true);

-- Allow authenticated users to insert/update venues (customize as needed)
CREATE POLICY "Authenticated users can manage venues." ON venues FOR ALL USING (auth.role() = 'authenticated');

-- Allow authenticated users to insert/update events (customize as needed)
CREATE POLICY "Authenticated users can manage events." ON events FOR ALL USING (auth.role() = 'authenticated');

-- Insert sample data for testing (optional)
INSERT INTO venues (venue_name, country, address, city, state, zip_code) VALUES
('Madison Square Garden', 'USA', '4 Pennsylvania Plaza', 'New York', 'NY', '10001'),
('Hollywood Bowl', 'USA', '2301 N Highland Ave', 'Los Angeles', 'CA', '90028'),
('Royal Albert Hall', 'UK', 'Kensington Gore', 'London', '', 'SW7 2AP');

INSERT INTO events (event_title, description, venue_id, date, event_hour, price, hoster) VALUES
('Summer Music Festival', 'Annual outdoor music festival featuring top artists', 1, '2024-07-15', '19:00:00', 75.00, 'Live Nation'),
('Comedy Night Special', 'Stand-up comedy show with renowned comedians', 2, '2024-08-20', '20:30:00', 45.50, 'Comedy Central'),
('Classical Concert', 'Evening of classical music performances', 3, '2024-09-10', '19:30:00', 120.00, 'Royal Philharmonic');

-- Note: In Supabase, permissions are handled through RLS policies and the auth system
-- No explicit GRANT statements needed for basic operations

-- Verify the schema creation
SELECT 
    table_name, 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
    AND table_name IN ('events', 'venues')
ORDER BY table_name, ordinal_position;

-- Additional verification for Supabase
SELECT 
    schemaname,
    tablename,
    tableowner,
    hasindexes,
    hasrules,
    hastriggers
FROM pg_tables 
WHERE schemaname = 'public' 
    AND tablename IN ('events', 'venues');
